---
title: "Mason_Model"
output: html_document
---

## Setup
```{r}
# Load Packages
library(here)
library(ggplot2)
library(tidyverse)
library(naniar)
library(gtsummary)
library(broom)
library(DHARMa)

# Load in data
kelp_data <- read_csv("PISCO_kelpforest_swath.1.2.csv")

fish_data <- read_csv("pisco_fish.csv")
```
### 1. Define Research Question
#### Are depth, size, month, year, and zone significant predictors of disease presence in kelp in UCSC's kelp forest?

### Tidy Data
```{r}
kelp_disease_data <- kelp_data %>% 
  filter(disease %in% c("SEVERE",
                        "MILD",
                        "YES",
                        "WASTING",
                        "BLACK SPOT",
                        "HEALTHY")) %>%
  mutate(disease_clean = case_when(
    disease %in% c("WASTING",
                   "BLACK SPOT",
                   "YES",
                   "SEVERE",
                   "MILD") ~ "Yes",
    disease == "HEALTHY" ~ "No",
    TRUE ~ NA_character_
  )) %>% 
  filter(campus == "UCSC") %>%
  select(-observer,
         -notes,
         -site_name_old,
         -campus,
         -method,
         -survey_year,
         -disease) %>%
  mutate(disease_binary = ifelse(disease_clean == "Yes", 1, 0),
         month = factor(month),
    year = factor(year),
    site = factor(site)
  ) %>% 
  drop_na()
```

### 2. Examine Data and Possible Correlations
```{r}
# Raw values for kelp disease
chart_kelp_disease <- ggplot(kelp_disease_data, aes(x = disease_clean)) +
  geom_bar() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

chart_kelp_disease


# Raw values for depth
chart_depth <- ggplot(kelp_disease_data,
                      aes(x = depth)) + 
  geom_bar() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90,
                                   hjust = 1))
chart_depth

# Raw values for vegetation zone
chart_vegetation_zone <- ggplot(df_side_blotched,
                      aes(x = zone)) + 
  geom_bar() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90,
                                   hjust = 1))
chart_vegetation_zone

# Raw values for whole tails
chart_tails <- ggplot(df_side_blotched,
                      aes(x = tail)) + 
  geom_bar() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90,
                                   hjust = 1))
chart_tails
```

### 3. Fit Regression Model
### 4. Evaluate Model Diagnostics
### 5. Interpret the Model and Communicate the Results



```{r}
model <- glm(
  disease_binary ~
    depth +
    size +
    month +
    year +
    zone,
  data = kelp_disease_data,
  family = "binomial"
)
summary(model)

simulateResiduals(model) %>% 
  plot()
```

